### ISSUE TITLE
Not all crashes types are handled on Windows, probably unintentionally

### ISSUE THREAD

**Issue by dmitrio95** [dschmidt/libcrashreporter-qt#19]
Testing libcrashreporter-qt on Windows reveals that some crashes are not handled by this library. The reason is that `google_breakpad::ExceptionHandler` object is constructed in a way similar to that on other operational systems:
https://github.com/dschmidt/libcrashreporter-qt/blob/45361826acef3177ad8cf0199e51764eec708694/src/libcrashreporter-handler/Handler.cpp#L248-L253
The `true` parameter corresponds to [`install_handler`](https://github.com/dschmidt/libcrashreporter-qt/blob/45361826acef3177ad8cf0199e51764eec708694/3rdparty/breakpad/client/mac/handler/exception_handler.h#L111) boolean parameter that is common to Linux and MacOS handlers. However `ExceptionHandler` on Windows handles different types of crashes in separate ways and requires a more fine-grained choice of which handlers should be enabled. The constructor called by libcrashreporter-qt is this one:
https://github.com/dschmidt/libcrashreporter-qt/blob/45361826acef3177ad8cf0199e51764eec708694/3rdparty/breakpad/client/windows/handler/exception_handler.h#L210-L215
and that `true` parameter corresponds to `handler_types` parameter of type `int`. So an implicit `bool` to `int` conversion takes place (which is probably not intended here) and [`HANDLER_EXCEPTION`](https://github.com/dschmidt/libcrashreporter-qt/blob/45361826acef3177ad8cf0199e51764eec708694/3rdparty/breakpad/client/windows/handler/exception_handler.h#L153) handler gets chosen. This enables installation of exception handler via `SetUnhandledExceptionFilter` but this still doesn't catch some other types of crashes like pure virtual member function calls. In order to handle all crash types supported by Breakpad this parameter should be set to `HANDLE_ALL`. I added the patch making this change to the PR #18 but perhaps some other solution would be preferred in case `HANDLE_ALL` is not used here on purpose.

**Comment by dmitrio95** [comment]
Should be fixed now, the pull request got merged.

**Comment by dschmidt** [comment]
Again sorry for the delay, no idea why I completely missed to merge that PR.
