### ISSUE TITLE
V1 see alg

### ISSUE THREAD

**Issue by ihsinme** [dschmidt/libcrashreporter-qt#20]
https://github.com/dschmidt/libcrashreporter-qt/blob/293bdfb92c9be0ee71e90476e9cf5558c4344317/src/libcrashreporter-gui/linux-backtrace-generator/crqt-kmacroexpander_unix.cpp#L97-L258

**Comment by dschmidt** [comment]
hm?

**Comment by ihsinme** [comment]
sorry

вт, 14 июл. 2020 г., 17:07 Dominik Schmidt <notifications@github.com>:
