### ISSUE TITLE
C11 not supported

### ISSUE THREAD

**Issue by codeyash** [dschmidt/libcrashreporter-qt#6]
Its failed to build with c11 enabled.

C11 is not supported by breakpad so its not by this lib as well. But we can use https://github.com/Mendeley/breakpad or other which supports C11

Or Patch can be used from above library author 
as mentioned here https://code.google.com/p/google-breakpad/issues/detail?id=481

**Comment by dschmidt** [comment]
If we can't fix it properly upstream, we can most likely apply some sort of fix/hack ...

Just talked to ted (@luser) of breakpad fame and he suggested to first submit the fix to  src/third_party/lss/linux_syscall_support.h to https://code.google.com/p/linux-syscall-support/ 
Then submit the other changes together with an updated linux-syscall-support to breakpad.

Could you do that? 

Until then you could give https://github.com/dschmidt/libcrashreporter-qt/pull/4 a shot.

**Comment by codeyash** [comment]
This solved problem

https://github.com/codeyash/breakpad-qt/blob/master/breakpad/src/common/linux/typeof.h

Instead of type replace with TYPEOF based on above file and now everything complies properly.

I don't know if it is like hack/patch or any side-effect but for now it works perfectly.

**Comment by dschmidt** [comment]
sorry for not responding on irc. I didnt see the query.

Can you try to get the changes upstream please?

**Comment by jon-turney** [comment]
I have submitted a patch upstream to fix building breakpad with --std=c++11
https://breakpad.appspot.com/7824002/

I cannot reproduce the build problem in lss which the Mendeley patch addresses

Building gtest (required for 'make check') with --std=c++11 looks like it needs a later version of gtest than the one currently included in breakpad.

**Comment by dschmidt** [comment]
@teo aren't you compiling on linux with c++11? Does that mean it werks now?

**Comment by teo** [comment]
I am compiling Calamares with C++11, but I don't know whether libcrashreporter and/or Breakpad locally changes the compiler flag.
