### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by codeyash** [dschmidt/libcrashreporter-qt#7]
I appreciate work under GPL but it restrict to hide modified code or to use in closed source.

If possible please license it dual GPL plus LPGL, Apache, BSD, MIT 
These licence will make sure you will get your copyright and name.

Also it will make compatible with breakpad itself which is under  BSD 3-Clause ( Similar to Apache).

Different license from breakpad will only means only GPL based license app can use it and not all apps which are using breakpad. It restricts userbase. So please take as request to release with dual license.

I personally use Apache for all my codes.

Here is my attempt : https://github.com/codeyash/breakpad-qt

**Comment by dschmidt** [comment]
You can't simply take our code and put an incompatible Apache license file in the main dir. That's not how it works. We can talk about changing the license, but right now you're violating it.

**Comment by dschmidt** [comment]
Or at least you are tricking people finding your repo and not looking at license headers in the files into violating it.

**Comment by codeyash** [comment]
Yes I understand that's why I want your permission. 

https://github.com/codeyash/breakpad-qt/issues/1

I guess you know who is Chris. Please ask him that I'm already in talk with you and I don't believe in illegal activity. Let me know how to proceed.

You want me to fork? or Anything else.

Unless you allow us dual license this is pretty much useless for me you know why.
Again, I request please allow me to use this under Apache or MIT or BSD. Whatever suits best for you.

-Yash

**Comment by codeyash** [comment]
Here is your violation. Kind of. No credit even in README.

https://github.com/RedisDesktop/CrashReporter

**Comment by danimo** [comment]
> Yes I understand that's why I want your permission.

@codeyash What domme means is by committing the license you have effectively put your code under said license. So if someone else comes along he will think you had the right to do the re-licensing. 

That said, the only ones authorized to change the license (as in: craft and commit the change) are @dschmidt and @muesli as the authors.

I know you didn't mean to do this is bad faith, but it's still a license violation as-is. I'd recommend to remove that commit and let the two take action.

**Comment by codeyash** [comment]
ok sure got it. I already removed repo. I understood my mistake and corrected that.

If only single product can get permission or like expection would be enough for me. For that I will include your copyright and name in product credit list. I can't buy anything for now. No funds. ;(.

Please let me know how to proceed. 

-Yash

**Comment by codeyash** [comment]
I take my request back. I will design my own. 

-Yash
