### ISSUE TITLE
Without cmake attempt or Qmake version

### ISSUE THREAD

**Issue by codeyash** [dschmidt/libcrashreporter-qt#8]
Not a issue. Just want to notify you.

https://github.com/codeyash/breakpad-qt

Attempt includes:
* Qmake based
* c11 Supported
* Latest breakpad

If possible add this in your readme so that anyone who wants to use based on qmake can use this.

Rest is pretty much your stuff  :)

Thanks,
Yash

**Comment by dschmidt** [comment]
Why dont you send a PR so I can incorporate your qmake work into my lib directly? Much better than rederencing a fork in the Readme. If you say latest breakpad, do you mean latest version by jon turney or upstream? The latter breaks mingw support.

**Comment by codeyash** [comment]
I can share code I committed on deleted repo. You can commit that work under your name. I've no problem. Due to licensing issue I no longer have much interested. I have to design my own.
